// import { Vector2d, Grid } from '../util/grid';

// export const description = `
// --- Day 10: The Stars Align ---
// It's no use; your navigation system simply isn't capable of providing walking directions in the arctic circle, and certainly not in 1018.

// The Elves suggest an alternative. In times like these, North Pole rescue operations will arrange points of light in the sky to guide missing Elves back to base. Unfortunately, the message is easy to miss: the points move slowly enough that it takes hours to align them, but have so much momentum that they only stay aligned for a second. If you blink at the wrong time, it might be hours before another message appears.

// You can see these points of light floating in the distance, and record their position in the sky and their velocity, the relative change in position per second (your puzzle input). The coordinates are all given from your perspective; given enough time, those positions and velocities will move the points into a cohesive message!

// Rather than wait, you decide to fast-forward the process and calculate what the points will eventually spell.

// For example, suppose you note the following points:

// position=< 9,  1> velocity=< 0,  2>
// position=< 7,  0> velocity=<-1,  0>
// position=< 3, -2> velocity=<-1,  1>
// position=< 6, 10> velocity=<-2, -1>
// position=< 2, -4> velocity=< 2,  2>
// position=<-6, 10> velocity=< 2, -2>
// position=< 1,  8> velocity=< 1, -1>
// position=< 1,  7> velocity=< 1,  0>
// position=<-3, 11> velocity=< 1, -2>
// position=< 7,  6> velocity=<-1, -1>
// position=<-2,  3> velocity=< 1,  0>
// position=<-4,  3> velocity=< 2,  0>
// position=<10, -3> velocity=<-1,  1>
// position=< 5, 11> velocity=< 1, -2>
// position=< 4,  7> velocity=< 0, -1>
// position=< 8, -2> velocity=< 0,  1>
// position=<15,  0> velocity=<-2,  0>
// position=< 1,  6> velocity=< 1,  0>
// position=< 8,  9> velocity=< 0, -1>
// position=< 3,  3> velocity=<-1,  1>
// position=< 0,  5> velocity=< 0, -1>
// position=<-2,  2> velocity=< 2,  0>
// position=< 5, -2> velocity=< 1,  2>
// position=< 1,  4> velocity=< 2,  1>
// position=<-2,  7> velocity=< 2, -2>
// position=< 3,  6> velocity=<-1, -1>
// position=< 5,  0> velocity=< 1,  0>
// position=<-6,  0> velocity=< 2,  0>
// position=< 5,  9> velocity=< 1, -2>
// position=<14,  7> velocity=<-2,  0>
// position=<-3,  6> velocity=< 2, -1>
// Each line represents one point. Positions are given as <X, Y> pairs: X represents how far left (negative) or right (positive) the point appears, while Y represents how far up (negative) or down (positive) the point appears.

// At 0 seconds, each point has the position given. Each second, each point's velocity is added to its position. So, a point with velocity <1, -2> is moving to the right, but is moving upward twice as quickly. If this point's initial position were <3, 9>, after 3 seconds, its position would become <6, 3>.

// Over time, the points listed above would move like this:

// Initially:
// ........#.............
// ................#.....
// .........#.#..#.......
// ......................
// #..........#.#.......#
// ...............#......
// ....#.................
// ..#.#....#............
// .......#..............
// ......#...............
// ...#...#.#...#........
// ....#..#..#.........#.
// .......#..............
// ...........#..#.......
// #...........#.........
// ...#.......#..........

// After 1 second:
// ......................
// ......................
// ..........#....#......
// ........#.....#.......
// ..#.........#......#..
// ......................
// ......#...............
// ....##.........#......
// ......#.#.............
// .....##.##..#.........
// ........#.#...........
// ........#...#.....#...
// ..#...........#.......
// ....#.....#.#.........
// ......................
// ......................

// After 2 seconds:
// ......................
// ......................
// ......................
// ..............#.......
// ....#..#...####..#....
// ......................
// ........#....#........
// ......#.#.............
// .......#...#..........
// .......#..#..#.#......
// ....#....#.#..........
// .....#...#...##.#.....
// ........#.............
// ......................
// ......................
// ......................

// After 3 seconds:
// ......................
// ......................
// ......................
// ......................
// ......#...#..###......
// ......#...#...#.......
// ......#...#...#.......
// ......#####...#.......
// ......#...#...#.......
// ......#...#...#.......
// ......#...#...#.......
// ......#...#..###......
// ......................
// ......................
// ......................
// ......................

// After 4 seconds:
// ......................
// ......................
// ......................
// ............#.........
// ........##...#.#......
// ......#.....#..#......
// .....#..##.##.#.......
// .......##.#....#......
// ...........#....#.....
// ..............#.......
// ....#......#...#......
// .....#.....##.........
// ...............#......
// ...............#......
// ......................
// ......................
// After 3 seconds, the message appeared briefly: HI. Of course, your message will be much longer and will take many more seconds to appear.

// What message will eventually appear in the sky?
// `;

// type MovingPoint = [Vector2d, Vector2d];

// function isInBounds([x, y]: Vector2d, [width, height]: Vector2d): boolean {
//     return x >= 0 && y > 0 && x < width && y < height;
// }

// function tick(points: MovingPoint[], tickNunber: number, dimensions: Vector2d): boolean {
//     console.log(`tick ${tickNunber}`);
//     points.forEach((p, i) => (points[i][0] = movePoint(p)));
//     const allPointsInRange = points.some(([point]) => isInBounds(point, dimensions));

//     if (allPointsInRange) {
//         console.log(`all points are visible after ${tickNunber} ticks.`);
//         return true;
//     }

//     return false;
// }

// function getConsoleDimensions(): Vector2d {
//     return [process.stdout.columns, process.stdout.rows];
// }

// function movePoint([[x, y], [vx, vy]]: MovingPoint, ticks = 1): Vector2d {
//     // console.log(`[${x}, ${y}] => [${x + vx * ticks}, ${y + vy * ticks}]`);
//     return [x + vx * ticks, y + vy * ticks];
// }

// function plotPoints(points: MovingPoint[]): void {
//     const [w, h] = getConsoleDimensions();
//     const grid = new Grid<string>(w, h);

//     points.forEach(([p]) => grid.put(p, '*'));

//     console.log(grid.toString());
// }

// function parseLine(input: string): MovingPoint {
//     const matches = /^position=<\s*(-?\d+),\s*(-?\d+)> velocity=<\s*(-?\d+),\s*(-?\d+)>$/.exec(
//         input
//     );
//     if (!matches) throw new Error('Regex did not match anything');
//     matches.shift(); // remove fullmatch
//     const [px, py, vx, vy] = matches.map((n) => Number(n));

//     return [
//         [px, py],
//         [vx, vy],
//     ];
// }

// export function solvePart1(input: string[]): string {
//     const points = input.map(parseLine);

//     const terminalDimensions = getConsoleDimensions();
//     let result = false;
//     for (let i = 0; i < 100000; i++) {
//         result = tick(points, i, terminalDimensions);
//         if (result) {
//             for (let j = i; j < i + 50; j++) {
//                 tick(points, i, terminalDimensions);
//                 plotPoints(points);
//             }
//             console.log('done');
//             break;
//         }
//     }

//     return '';
// }
